![Images](Images/ITAcademy.png)
# DATA SCIENCE: S02.T04
#### Created by: Dani Planas Montserrat


In [11]:
##########################################################################
##           DATA SCIENCE: S02.T04: Nivell 1 Exercici 1                 ##
##########################################################################
# Exercici 1: Crea una funció que donat un Array d’una dimensió, et faci
# un resum estadístic bàsic de les dades. Si detecta que l’array té més 
# d’una dimensió, ha de mostrar un missatge d’error.



#********************************    Functions   ********************************
def arrayShowStat(inArray):
    txtResult=''
    #Check if Array have 1D or more
    if (inArray.ndim==1): 
        
        txtResult = "RESUM ESTADÍSTIC:"
        txtResult += "\n La mitja Aritmètica: " + str(inArray.mean()) 
        txtResult += "\n Mitjana: " + str(np.median(inArray))
        txtResult += "\n Desviació: " + str(np.std(inArray))
        txtResult += "\n Valor acumulatiu: " + str(inArray.sum())
        txtResult += "\n Valor mínim: " + str(inArray.min())
        txtResult += "\n Valor màxim: " + str(inArray.max())
    else:
      txtResult = "Error! L'array té més d'una dimensió. "
    return txtResult

#********************************       Main     ********************************
#import library
import numpy as np

## create Variables
myArray = np.array([1, -3, 12, 11, 10, 10, 10, 10], dtype='i8')
myArrayEmpty =  np.empty((3,2)) 
result=''

#Print Result
result = arrayShowStat(myArray)
print (result)


RESUM ESTADÍSTIC:
 La mitja Aritmètica: 7.625
 Mitjana: 10.0
 Desviació: 5.12195031213697
 Valor acumulatiu: 61
 Valor mínim: -3
 Valor màxim: 12


In [7]:
##########################################################################
##           DATA SCIENCE: S02.T04: Nivell 1 Exercici 2                 ##
##########################################################################
# Exercici 2: Crea una funció que et generi un quadrat NxN de nombres 
# aleatoris entre el 0 i el 100.

#********************************    Functions   ********************************
#*******    Request Number Integer    *******
def reqNumberInt(msgTxt, limMin, limMax):
    
    #create local variables
    userNum = 0
    valueOK = False
    
    #Request number
    while valueOK != True:
          userNum = int(input(msgTxt))
          valueOK = checkLimits("Error! El valor ha d'estar entre els límits", userNum, limMin, limMax)

    return userNum
#*******    Check if a number is between limits    *******
def checkLimits(msg, userNum, limMin, limMax):
    #create local variables
    result = False;   
    # Check if value is within limits
    if ((userNum>=limMin) & (userNum<=limMax)):
          # Value OK
          result = True;
    else:
          result = False;
          #Error Message
          print(msg, limMin,   " i " , limMax , " .");	#Print Line

    return result
#*******    Create an Array N1*N2 with random numbers    *******
def arrayCreate(N1,N2):
    txtResult=''
    #Check if Array have 1D or more
    myArrayEmpty =  np.random.randint(1,100, size=(N1,N2))

    return myArrayEmpty

#********************************       Main     ********************************
## create Variables
N1 = 0

N1 = reqNumberInt('Introdueix la dimensión de la matriu, N*N:  ', 1, 10)
#Create an array
myArray = arrayCreate(N1,N1)
#Print Result
print (myArray)


Introdueix la dimensión de la matriu, N*N:  3
[[78 62 92]
 [20 10  9]
 [20 93 34]]


In [4]:
##########################################################################
##           DATA SCIENCE: S02.T04: Nivell 1 Exercici 3                 ##
##########################################################################
# Exercici 3: Crea una funció que donada una taula de dues dimensions, 
# et calculi els totals per fila i els totals per columna.

#********************************    Functions   ********************************
#*******    Request Number Integer    *******
def reqNumberInt(msgTxt, limMin, limMax):
    
    #create local variables
    userNum = 0
    valueOK = False
    
    #Request number
    while valueOK != True:
          userNum = int(input(msgTxt))
          valueOK = checkLimits("Error! El valor ha d'estar entre els límits", userNum, limMin, limMax)

    return userNum
#*******    Check if a number is between limits    *******
def checkLimits(msg, userNum, limMin, limMax):
    #create local variables
    result = False;   
    # Check if value is within limits
    if ((userNum>=limMin) & (userNum<=limMax)):
          # Value OK
          result = True;
    else:
          result = False;
          #Error Message
          print(msg, limMin,   " i " , limMax , " .");	#Print Line

    return result
#*******    Create an Array N1*N2 with random numbers    *******
def arrayCreate(N1,N2):
    txtResult=''
    #Create an Array with random values from 1 to 100
    myArrayEmpty =  np.random.randint(1,100, size=(N1,N2))

    return myArrayEmpty
#*******    Calcl sum from Columns & Rows    *******
def arraySumDim(inArray):
    txtResult=''
    #Check if Array have 2D 
    if (inArray.ndim==2): 
        
        txtResult = "VALORS TOTALS:"
        txtResult += "\n Suma Columnes: " + str(np.sum(inArray, axis=0)) 
        txtResult += "\n Suma Files: "    + str(np.sum(inArray, axis=1)) 
    else:
      txtResult = "Error! L'array no té 2 dimensions (2D). "
    return txtResult


#********************************       Main     ********************************
## create Variables
N1 = 0
txtResult = ''

N1 = reqNumberInt('Introdueix la dimensión de la matriu, N*N:  ', 1, 10)

myArray = arrayCreate(N1,N1)          #Create an array
txtResult = arraySumDim(myArray)      #Sum Dimensions from Array 2D

#Print Result
print (myArray)
print (txtResult)



Introdueix la dimensión de la matriu, N*N:  3
[[36 37 32]
 [72 67 90]
 [36 36 15]]
VALORS TOTALS:
 Suma Columnes: [144 140 137]
 Suma Files: [105 229  87]


In [84]:
##########################################################################
##           DATA SCIENCE: S02.T04: Nivell 1 Exercici 4                 ##
##########################################################################
# Exercici 4: Implementa manualment una funció que calculi el coeficient 
# de correlació. Informa’t-en sobre els seus usos i interpretació.

#import library
import math
#********************************    Functions   ********************************
#*******    Create an Array N1*N2 with random numbers    *******
def arrayCreate(N1,N2):
    txtResult=''
    #Create an Array with random values from 1 to 100
    myArrayEmpty =  np.random.randint(1,100, size=(N1,N2))

    return myArrayEmpty
#*******    Calculation Correlation Coefficient    *******
def arrayCalcCorrCoef(inArray1,inArray2):
    txtResult=''
    
    arrayXY= np.multiply(inArray1,inArray2)
    arrayX2= np.multiply(inArray1,inArray1)
    arrayY2= np.multiply(inArray2,inArray2)
    sumX = np.sum(inArray1)
    sumY = np.sum(inArray2)
    sumXY = np.sum(arrayXY)
    sumX2 = np.sum(arrayX2)
    sumY2 = np.sum(arrayY2)
    
    xMean = np.mean(inArray1)
    yMean = np.mean(inArray2)
    cov =  ((sumXY/inArray1.size) - (xMean*yMean))
    dX = math.sqrt((sumX2/inArray1.size)-(xMean*xMean))
    dY = math.sqrt((sumY2/inArray2.size)-(yMean*yMean))
    corr = cov/(dX*dY)
    
    print("X",inArray1)
    print("Y",inArray2)
    print("XY",arrayXY)
    print("X2",arrayX2)
    print("Y2",arrayY2)
    print("Suma X:",sumX)
    print("Suma Y:",sumY)
    print("Suma XY:",sumXY)
    print("Suma X2:",sumX2)
    print("Suma Y2:",sumY2)
    print("Mitja Aritmètica X:",xMean)
    print("Mitja Aritmètica Y:",yMean)
    print("Elementos:",inArray1.size)   
    print("Covariança:",cov)  
    print("Desviació Típica X:",dX)  
    print("Desviació Típica Y:",dY)  
    print("\n")  
    
    
    txtResult = "VALORS CALCULATS:"
    txtResult += "\n Correlació (càlcul Manual): " + str(corr) 
    txtResult += "\n Correlació (càlcul npArray): \n" + str(np.corrcoef(myArray1, myArray2)) 
    return txtResult


#********************************       Main     ********************************
## create Variables
N1 = 0
txtResult = ''


myArray1 = np.array([1, 3, 4, 4, 5, 6, 6, 7, 7, 8, 10, 10], dtype='i8')
myArray2 = np.array([1, 2, 2, 4, 4, 4, 6, 4, 6, 7, 9, 10], dtype='i8')
txtResult = arrayCalcCorrCoef(myArray1,myArray2)      

#Print Result
print (txtResult)


X [ 1  3  4  4  5  6  6  7  7  8 10 10]
Y [ 1  2  2  4  4  4  6  4  6  7  9 10]
XY [  1   6   8  16  20  24  36  28  42  56  90 100]
X2 [  1   9  16  16  25  36  36  49  49  64 100 100]
Y2 [  1   4   4  16  16  16  36  16  36  49  81 100]
Suma X: 71
Suma Y: 59
Suma XY: 427
Suma X2: 501
Suma Y2: 375
Mitja Aritmètica X: 5.916666666666667
Mitja Aritmètica Y: 4.916666666666667
Elementos: 12
Covariança: 6.493055555555554
Desviació Típica X: 2.5967394084804796
Desviació Típica Y: 2.660148283252061


VALORS CALCULATS:
 Correlació (càlcul Manual): 0.9399719717326368
 Correlació (càlcul npArray): 
[[1.         0.93997197]
 [0.93997197 1.        ]]
